config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: 'romances#index'
  resources :romances do
    
    
    collection do
      get 'search'
    end

    member do
      get 'kaiketu'
    end

    member do
      get 'checked'
    end
    
    resources :comments 



  end

  post 'like/:id' => 'likes#create', as: 'create_like'

  # 以下の1行を追記
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  get 'users', to: 'users#check'


  
end

app/views/shared/_error_messages.html.erb
  <%#= binding.pry %>
<% if model.errors.any? %>
  <%#= binding.pry %>
  <div class="error-message1">
  </div>

  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%#= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>

<%# localhost:3000/tweets/search?keyword=7&commit=検索 %>
<%# localhost:3000/?keyword=大好き&commit=検索 %>

<header class='top-page-header'>


  <div class='search-bar-contents'>
    <%= link_to image_tag("名称未設定2.png", class:"furima-icon"), "/" %>
     <%= form_with(url: search_romances_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワードを検索してね！", class: "input-box", required: true %>
           <%# <div class="register-btn">  %>
                  <%= form.submit "検索", class: "a112-btn" %>
            <%# </div> %>
    <% end %>
  </div>

  
          <div class='nav'>
            <ul class='lists-left'>
              <li><%= link_to '       ', "#", class: "category-list" %></li>
              <li><%= link_to '       ', "#", class: "brand-list" %></li>
     
            </ul>
            <ul class='lists-right'>
              <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
              <% if user_signed_in? %>
                <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li> 
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
              <% else %>
                <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
                <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
                <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
              <% end %>
            </ul>
          </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>


  <div class='second-fotter-text-wrap'>
     <%= Date.today  %>
     <% d = Date.today %>

   <%= %w(日 月 火 水 木 金 土)[d.wday] + '曜日' %>
        現在
  <%#= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
  <div id="DateTimeDisp"></div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("nature-214823.png", class:"second-logo"), "/" %>
  <%#= link_to "トップページに戻る", "/" %>
</header>