config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: 'romances#index'
  resources :romances do
    
    
    collection do
      get 'search'
    end

    member do
      get 'kaiketu'
    end

    member do
      get 'checked'
    end
    
    resources :comments 



  end

  post 'like/:id' => 'likes#create', as: 'create_like'

  # 以下の1行を追記
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  get 'users', to: 'users#check'


  
end

app/models/romance.rb
class Romance < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  has_many :likes, dependent: :destroy

  # バリデーション----------------------------------------------

  with_options presence: { message: 'を選択してください' } do
    validates :image
  end

  # validates :image, presence: true

  validates :title, length: { in: 5..30 }

  validates :info1, length: { in: 8..1000 }
end

app/controllers/romances_controller.rb
class RomancesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_romance, only: %i[show edit update destroy]

  def index
    # @romances = Romance.order('created_at DESC')
    @romances = Romance.page(params[:page]).per(2).order('created_at DESC')
  end

  def show
    #    @romance = Romance.find(params[:id])

    @comment = Comment.new
    @comments = @romance.comments.includes(:user).order('created_at DESC')
  end

  def new
    @romance = Romance.new
  end

  def create
    @romance = Romance.new(romance_params)

    # --------------------------------------------------------------

    # 以下の1行を追記
    @romance.user_id = current_user.id

    respond_to do |format|
      if @romance.save
        format.html { redirect_to @romance, notice: 'Romance was successfully created.' }
        format.json { render :show, status: :created, location: @romance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @romance.errors, status: :unprocessable_entity }
      end
    end
    # --------------------------------------------------------------
  end

  def destroy
    @romance.destroy

    respond_to do |format|
      format.html { redirect_to romances_url, notice: 'Romance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def update
    if @romance.update(romance_params_update)
      # binding.pry
      redirect_to romance_path(@romance.id)
    else
      render :edit
    end
  end

  def search
    # @romances = SearchRomancesService.search(params[:keyword])

    # キーワード分割
    keywords = params[:keyword].split(/[[:blank:]]+/).select(&:present?)

    # 空のモデルオブジェクト作成（何も入っていない空配列のようなもの）
    @romances = Romance.none

    # 検索ワードの数だけor検索を行う
    keywords.each do |keyword|
      @romances = @romances.or(Romance.where('title LIKE ?', "%#{keyword}%"))
    end
  end

  def checked
    comment = Comment.find(params[:id])

    if comment.checked
      comment.update(checked: false)
    else
      comment.update(checked: true)
    end

    item = Comment.find(params[:id])
    render json: { comment: item }
  end

  def kaiketu
    romance = Romance.find(params[:id])

    if romance.kaiketu
      romance.update(kaiketu: false)
    else
      romance.update(kaiketu: true)
    end

    item = Romance.find(params[:id])
    render json: { romance: item }
  end

  private

  def romance_params
    params.require(:romance).permit(:image, :title, :info1).merge(user_id: current_user.id)
  end

  def set_romance
    @romance = Romance.find(params[:id])
  end

  def romance_params_update
    params.require(:romance).permit(:image, :title, :info1)
  end
end

app/helpers/romances_helper.rb
module RomancesHelper
  def romance_lists(romances)
    html = ''
    romances.each do |romance|
      html += render(partial: 'romance', locals: { romance: romance })
    end
    raw(html)
  end
end

app/views/romances/_romance.html.erb
 <% if user_signed_in? %>  
  <%# 「liked_by?(post.id)」は、ユーザーが「いいね」を押しているかどうかを判別するためのメソッド %>
    <%# binding.pry %>


      <% if current_user.liked_by?(romance.id) %>     
          <td>
            観閲済マークをはずす
                            <%# binding.pry %>
            <%= link_to destroy_like_path(romance), class: "like-link", data: { confirm: '本当に取り消しますか？' }, method: :DELETE, remote: true do %>
              <i class="fa fa-heart unlike-btn"></i>
            <% end %>
            <%= romance.likes.count %>
          </td>
      <% else %>
          <td>
              観閲済マークを付ける
                  <%# binding.pry %>
              <%= link_to create_like_path(romance), class: "like-link", method: :POST, remote: true do %>
                <i class="fa fa-heart like-btn"></i>
              <% end %>
            <%= romance.likes.count %>
          </td>
      <% end %>

<% else %>

    <td> 読者:閲覧数<%= romance.likes.count %> </td>
          
 <% end %>



 <%#= button_to '応援してるよを取り消す', romance_like_path(@romance), method: :delete , class: "item-red-btn", data: { confirm: '本当に取り消しますか？' } %>

app/views/romances/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('名称未設定2.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">投稿を編集しましょう</h2>
    <%= form_with(model: @romance, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像を編集してね
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">(必須 40文字まで)</span>
      </div>
      <%= f.text_area :title, class:"items-text0", id:"item-name", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          悩みの説明
          <span class="indispensable">（必須 1,000文字まで）</span>
        </div>
        <%= f.text_area :info1, class:"items-text", id:"item-info",rows:"13" ,maxlength:"1000" %>
      </div>
    </div>


    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "編集完了" ,class:"sell-btn" %>
     <div>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

<%= render "shared/second-footer"%>

app/views/romances/index.html.erb
<script>
function rel() {
  if (window.name != "any") {
  
    location.reload();
    window.name = "any";
  } else {
    window.name = "";
  }
}
rel()
</script>


<%= render "shared/header" %>

<div class='main'>
  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      恋の疑問を解決するラブライク
    </h2>
    <p class='service-explain'>
      ラブライクは誰でも簡単に相談できる
    </p>
    <p class='service-explain'>
      全ての人の恋愛が成就するアプリです
      
    </p>
  </div>
</div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>


  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      みんな大好き！！ラブライクとは！？
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "4220178_s.png", class:"list-pict" %>
        <%# <span class='reason-list-number'>1</span> %>
        <h3 class='reason-list-text'>
          些細なことでも気軽に相談できる
        </h3>
        <%# <p class='reason-list-description'>
          自分で溜め込まずで皆に話そう！
        </p> %>
      </li>
      <li class='list'>
        <%= image_tag "4191062_l.png", class:"list-pict" %>
        <%# <span class='reason-list-number'>2</span> %>
        <h3 class='reason-list-text'>
          とっても簡単で検索もスムーズ
        </h3>
        <%# <p class='reason-list-description'>
          シンプルイズベストで検索もスムーズ！
        </p> %>
      </li>
      <li class='list'>
        <%= image_tag "4193334_m.png", class:"list-pict" %>
        <%# <span class='reason-list-number'>3</span> %>
        <h3 class='reason-list-text'>
          アドバイスで誰かを幸せにできる
        </h3>
        <%# <p class='reason-list-description'>
          みんなで恋を成就させよー！　　　　　　
        </p> %>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>


  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>

    <p class='ad-explain'>
      ラブライクは、日本の新時代を先駆ける最高のアプリ。
    </p>
    <p class='ad-explain'>
      登録者数・投稿数・回答数も業界トップを目指します！
    </p>
    <p class='ad-explain'>
      長年の疑問もここで解決できるかもしれません。
    </p>
  
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>


  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>さっそくアドバイスしてあげよう</h2>
    <%= link_to '新しい恋の相談', "#", class: "mybox" %>
  <ul class='item-lists'>
  <%# /商品一覧 %>

  <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
    <% if @romances[0] != nil %>  
        <% @romances.each do |romance| %>
          <li class='list'>
            <%= link_to romance_path(romance.id) do %>
              <div class='item-img-content'>
                <%= image_tag romance.image, class: "item-img" %>
                          <%# 商品が売れていればsold outを表示しましょう %>
                            <%# binding.pry %>
                            <% if romance.kaiketu %>
                               <div class='sold-out'> 
                                 <span>恋の悩み解決</span> 
                               </div> 
                            <% end %>
                          <%# //商品が売れていればsold outを表示しましょう %>
              </div>
              
              <div class='item-info'>
                  <h3 class='item-name'>
                    <%= romance.title %>        
                  </h3>
                  
                  <div class='item-price'>
                    名前：<%= romance.user.nickname %>
                  </div>

                  <div class='item-price'>
                    性別：<%= romance.user.seibetu.name %>
                  </div>

                  <div class='item-price'>
                    職業：<%= romance.user.work.name %>
                  </div>

                  <div class='item-price'>
                    読者：閲覧数 <%= romance.likes.count %>
                  </div>
                    <% if user_signed_in? %>  

                      <% if current_user.liked_by?(romance.id) %>   
                      既読済み  
                      <% end %>

                    <% end %>
              </div>

           
            <% end %>

          </li>
        <% end %>



  <%# -------------------------------------------------------------------------- %>
    <% else %>
      <%= link_to '#' do %>
        <%= image_tag "anime.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            記事を投稿してね！
          </h3>
          <div >
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

<%= link_to(new_romance_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>相談する</span>
  <%= image_tag '603344.png' , size: '585x50' ,class: "purchase-btn-icon" %>
<% end %>

 <div id="abcde" onclick="buttonClick()">
      <%= paginate @romances, class:"pagination1"%>
      <%= %>
</div>

<script>
  function buttonClick(){
    var a = document.documentElement;
    var y = a.scrollHeight - a.clientHeight;
    window.scroll(0, y);
      console.log(y); 
          console.log("wwwwwwwwww"); 
      }
   
</script>

<%= render "shared/second-footer"%>

app/views/romances/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('名称未設定2.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">悩みを投稿</h2>
    <%= form_with(model: @romance, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像を投稿してね
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">(必須 40文字まで)</span>
      </div>
      <%= f.text_area :title, class:"items-text0", id:"item-name", placeholder:"彼女のLINEがそっけないです。", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          悩みの説明
          <span class="indispensable">（必須 1,000文字まで）</span>
        </div>
        <%= f.text_area :info1, class:"items-text", id:"item-info", placeholder:"わたしには交際三ヶ月の彼女がいます。三日前のデートで割り勘にしたあたりから、彼女のLINEに絵文字がつかなくなりました。他の男には♥マークなどの絵文字など付けてしっかり丁寧に返してます。
やっぱり割り勘は単純にまずかったですかね？。。。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>


    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
     <div>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

<%= render "shared/second-footer"%>

app/views/romances/search.html.erb
<%# 検索結果の画面 %>
<%= render "shared/header" %>
    <%# binding.pry %>
 <div class='main'>



    <%# 商品一覧 %>
  <div class='item-contents'>
      <% if @romances[0] != nil %> 
        <h2 class='title'>あなたの気になる恋の相談はこれかな？</h2>
      <% else %>
        <h2 class='title'>その相談はまだないかも</h2>
        <%= link_to 'トップページに戻る', "/", class:"furima-icon1"%>
      <% end %>

      <%= link_to '検索した恋の相談', "#", class: "mybox" %>
  <ul class='item-lists'>
  <%# /商品一覧 %>


  <%# binding.pry %>

    <% if @romances[0] != nil %>  
        <% @romances.each do |romance| %>
          <li class='list'>
            <%= link_to romance_path(romance.id) do %>
              <div class='item-img-content'>
                <%= image_tag romance.image, class: "item-img" %>

                  <div class='item-info'>
                      <h3 class='item-name'>
                        <%= romance.title %>        
                      </h3>
                      <div class='item-price'>
                        名前：<%= romance.user.nickname %>
                      </div>
                        <div class='item-price'>
                        性別：<%= romance.user.seibetu.name %>
                      </div>
                      <div class='item-price'>
                        職業：<%= romance.user.work.name %>
                      </div>
                      <div class='item-price'>
                        読者：閲覧数 <%= romance.likes.count %>
                      </div>
                  </div>
              </div>
            <% end %>
          </li>
        <% end %>
      <% else %>
      
      <% end %>
</div>

app/views/romances/show.html.erb
<%= render "shared/header" %>


<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @romance.title %>
    </h2>

    <div class="box0">
        <%#= link_to '#', class:'abc' do %>
           <%# binding.pry %>

        <%= link_to "投稿者：#{@romance.user.nickname}", user_path(@romance.user.id),class:'abc' %>
         <%#= link_to "投稿者：#{@romance.user.nickname}", "/users/#{@romance.user.id}", class:'abc' %>
        
        
    </div>
    <div class="box1">
        <div class="boxz">
            <%= @romance.info1 %>
        </div>
    </div>
    
    <%# ログインユーザーか？ %>
    <% if user_signed_in? %>  
       <%# 投稿者とログインユーザーが同じ %>

      <% if current_user == @romance.user %>  
          <%= link_to '編集する', edit_romance_path(@romance.id), method: :get, class: "item-red-btn" %>
          <%= link_to '記事を削除', romance_path(@romance.id), method: :delete, class:'item-destroy' , data: { confirm: '本当に削除しますか？' } %>
      
                    
          <div  class="romance" data-id1=<%= @romance.id %> data-check1=<%= @romance.kaiketu %>>
            <div class="btn-gradient-3d1">解決したよ </div>
          </div>



        <% if @comments[0] != nil %>  

          <div class="container">
                  <%= form_with(model: [@romance, @comment], local: true) do |form| %>
                    <%# エラーメッセージ------------------------------------------------------------------------ %>
                      <div class='parent2'>
                      <%= render 'shared/error_messages', model: form.object %>
                      </div>
                    <%# エラーメッセージ------------------------------------------------------------------------ %>
                    <%= form.text_area :text, class:"box2", placeholder: "例）〇〇さん、アドバイスありがとう。何度もそのような話し合いはしているんですが。。。
        俺が悪かった直すと言って最後に機嫌取りをされての繰り返しで…冷めなんですかね…" , required: true %>
                      <div class='parent2'>
                        <%= form.submit "アドバイザーに返信" ,class:"a111-btn" %>
                      </div>
                  <% end %>
          </div>
         <% end %>

      <% else %>
  

          <div class="box15">
              <%= form_with(model: [@romance, @comment], local: true) do |form| %>
                    <%= render 'shared/error_messages', model: form.object %>
                    <%= form.text_area :text, class:"box2", placeholder: "例）「慣れ」と「飽き」がきているのかも。
        付き合いが長いと段々と好きとか甘い言葉を言うのはなんだか照れ臭くなってしまいますよね。
        安定した付き合いに慣れを感じて頑張って好かれていようとしなくなって扱いが雑になっていったり。
        もしかしたら、みんなの前での明るい彼は頑張ってつくっていてあなたの前のそれが素の状態なのかも。" , required: true %>
                    <div class="parent">
                      <%= form.submit "アドバイスを送信" ,class:"a111-btn" %>
                    </div>
              <% end %>
          </div>

      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
    </div>

     <%#= render 'shared/error_messages', model: form.object %>
    <div class="comments">
 
      <% if @comments %>
            <% @comments.each do |comment| %>
            
                  <div class="box1">
                   
                    <div class="box1a">
                      <% if comment.user == @romance.user %>  
                          投稿者本人：<%= comment.user.nickname %>  
                      <% else %>
                          アドバイザー：<%= comment.user.nickname %>
                      <% end %>
                   </div>

                  <div class="box1b">
                    <%= comment.text %> 
                  </div>
                    <% if user_signed_in? %>  
                        <div class="box1c">
                              <% if current_user == comment.user %>  
                                <%= link_to '編集', edit_romance_comment_path(@romance,comment), class:'box3c' %> 
                              <% end %>

                              <% if current_user == @romance.user %> 
                                  <% if @romance.user != comment.user %>  
                                    <%= link_to 'アドバイザーに返信', edit_romance_comment_path(@romance,comment), class:'box3c'  %>
                                  <% end %>
                                   <%= link_to '削除', romance_comment_path(@romance,comment.id), method: :delete , class:'box4c', data: { confirm: '本当に削除しますか？' } %>
                              <% end %>

                              <% if current_user != @romance.user %> 
                                  <% if current_user == comment.user %>  
                                    <%= link_to '削除', romance_comment_path(@romance,comment.id), method: :delete , class:'box4c', data: { confirm: '本当に削除しますか？' } %>
                                  <% end %>
                               <% end %>
                          </div>
                    <% end %>

                      <% if current_user == @romance.user %> 
                        <% if @romance.user != comment.user %>  
                          <div  class="comment" data-id=<%= comment.id %> data-check=<%= comment.checked %>>
                            <div class="btn-gradient-3d">アドバイス読んだよ </div>
                          </div>
                        <% end %>
                      <% end %>

                      <% if current_user != @romance.user %>
                          <% if current_user == comment.user %> 
                            <% if comment.checked %> 
                              <div  class="red1">投稿者：既読済み </div>
                            <% end %>
                          <% end %>
                      <% end %>

              </div>

            <% end %>

        <%# <%= link_to '削除', romance_comment_path(comment.id), method: :delete, class:'item-destroy' %> 
      <% else %>
          <div class="box1">
          アドバイザーとしてコメントを投稿しよう
          <p>例)彼女のLINEがそっけないです</p>
          </div>
      <% end %>
    </div>

      <% if current_user == @romance.user %> 
           <td> 読者:閲覧数<%= @romance.likes.count %> </td>

      <% else %>
           <%# binding.pry %>
        <table>
          <tbody>
              <tr id="romance_<%= @romance.id %>">
                <%#= render 'romance', romance: @romance %>   <%#  %>
                <%= render partial: 'romances/romance', locals: { romance: @romance } %>
              </tr>
          </tbody>
        </table>
      <% end %>




<div class="links0">

      <% if @romance.next.present? %>
        <div>
          <%= link_to "＜ 前の記事",romance_path(@romance.next), class: "change-item-btn" %>

        <%# else %>
         <%# <a href="#" class="change-item-btn">後ろの記事はありません</a> %>

      <% end %>
        </div>

    <% if @romance.previous.present? %>
      <div >
        <%= link_to "後ろの記事 ＞", romance_path(@romance.previous), class: "change-item-btn"%>
    
    <% else %>

    <a href="#" class="change-item-btn">後ろの記事はありません</a>

    <% end %>
        </div>

</div>


<%= render "shared/second-footer"%>